# Generated by Django 4.2.1 on 2023-06-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpenapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=1000)),
                ('ghostuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ghostpenapi.ghostuser')),
            ],
        ),
    ]
