# Generated by Django 4.2.1 on 2023-06-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpenapi', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
    ]
