# Generated by Django 4.2.1 on 2023-06-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpenapi', '0004_tag_alter_contact_ghostuser_letter_contacttag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='tags',
        ),
        migrations.AlterField(
            model_name='ghostuser',
            name='bio',
            field=models.CharField(max_length=10000),
        ),
    ]
