# Generated by Django 4.2.1 on 2023-06-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpenapi', '0005_remove_contact_tags_alter_ghostuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(related_name='contacts', through='ghostpenapi.ContactTag', to='ghostpenapi.tag'),
        ),
    ]
