# Generated by Django 4.2.1 on 2023-06-08 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpenapi', '0006_contact_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='user',
        ),
        migrations.AddField(
            model_name='letter',
            name='ghostuser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_letters', to='ghostpenapi.ghostuser'),
        ),
    ]
