# Generated by Django 4.2.2 on 2023-07-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpenapi', '0007_remove_letter_user_letter_ghostuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('contacts', models.ManyToManyField(related_name='campaigns', to='ghostpenapi.contact')),
                ('ghostuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ghostpenapi.ghostuser')),
            ],
        ),
    ]
