# Generated by Django 4.2.2 on 2023-07-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpenapi', '0009_campaign_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_letters', to='ghostpenapi.campaign'),
        ),
    ]
